# Generated by Django 4.2.19 on 2025-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmtgameid',
            name='game_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
