# Generated by Django 4.2.19 on 2025-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_gmtgameid_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmtgameid',
            name='game_id',
            field=models.CharField(help_text='get it from bradspelspriser.se', max_length=255, verbose_name='Bradspelpriset Game ID'),
        ),
    ]
